# Generated by Django 5.2.6 on 2025-09-15 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_initial'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthresponse',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='healthresponse',
            name='question',
        ),
        migrations.AddField(
            model_name='healthresponse',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.farm'),
        ),
    ]
